### ISSUE TITLE
按钮中，单选按钮名称显示异常

### ISSUE THREAD

**Issue by liumin0322** [ukui/qt5-ukui-platformtheme#12]
![2020-03-25 19-19-25屏幕截图](https://user-images.githubusercontent.com/48200161/77531267-9aa3d280-6ecd-11ea-8475-a496dc7b29aa.png)

**Comment by fenshezhuiyi** [comment]
之前画法不对,现对radio进行了重画.

**Comment by liumin0322** [comment]
20200328版本测试通过。
