### ISSUE TITLE
按钮中，工具按钮的悬浮异常

### ISSUE THREAD

**Issue by liumin0322** [ukui/qt5-ukui-platformtheme#13]
![2020-03-25 19-22-59屏幕截图](https://user-images.githubusercontent.com/48200161/77531546-1140d000-6ece-11ea-8181-b51fbcd87900.png)

**Comment by Yue-Lan** [comment]
新版本这个问题应该已经解决了，请@fenshezhuiyi 更新状态，关联提交号

**Comment by fenshezhuiyi** [comment]
关联 # b5fc630

**Comment by liumin0322** [comment]
20200328版本测试通过。
