### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by dou-y** [ukui/qt5-ukui-platformtheme#3]
I follow debian/control and install pre-depends with comands like:
`sudo apt install pkg-kde-tools libglib2.0-dev libqt5x11extras5-dev libkf5windowsystem-dev libgsettings-qt-dev pkg-config qt5-qmake qtbase5-dev qtbase5-dev-tools qtbase5-private-dev qtchooser qttools5-dev-tools`
After this, I use `debuild` and got this error:
![截屏2020-02-2614 05 00](https://user-images.githubusercontent.com/59866026/75316705-fe23eb80-58a0-11ea-9246-60700046a631.jpg)

**Comment by Yue-Lan** [comment]
The symbol file of libqt5-ukui-style1 is outdate. If a error happened duo to dpkg-gensymbol when debuild, the easiest way is delete *.symbol from debian/ directory.

**Comment by dou-y** [comment]
Thanks. I tried this method and it work. I'll close this issue.
