### ISSUE TITLE
输入部件中，“可编辑组合框”的文字显示有阴影

### ISSUE THREAD

**Issue by liumin0322** [ukui/qt5-ukui-platformtheme#8]

**Comment by liumin0322** [comment]
![2020-03-25 17-28-52屏幕截图](https://user-images.githubusercontent.com/48200161/77522058-915f3980-6ebe-11ea-8161-15e815dc621f.png)

**Comment by Yue-Lan** [comment]
@fenshezhuiyi 请确认状态

**Comment by fenshezhuiyi** [comment]
新版已经没有复现这个问题,如果有再出现,原因也是多写了一个drawtext,去掉即可.

**Comment by liumin0322** [comment]
20200328版本测试通过。
