### ISSUE TITLE
输入部件中，Lab和文本框中字体大小不一致

### ISSUE THREAD

**Issue by liumin0322** [ukui/qt5-ukui-platformtheme#9]
![2020-03-25 17-53-49屏幕截图](https://user-images.githubusercontent.com/48200161/77524004-9a053f00-6ec1-11ea-949e-b8e8a179df8f.png)

**Comment by Yue-Lan** [comment]
本周的提交应该已经修复了这个问题

**Comment by liumin0322** [comment]
20200328版本测试通过。
